name: geventmp
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
        python-version:
          - '3.12-dev'
          - '3.11'
          - '3.10'
          - '3.9'
          - '3.8'
          - '3.7'
          - 'pypy-3.8'
          - 'pypy-3.9'
        with-venv:
          - 'true'
          - 'false'
    env:
      DEPLOY_PYTHONS: "3.11"
      DEPLOY_OSES: "Linux"
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - shell: bash
        if: |
          github.event_name == 'push' &&
          contains(env.DEPLOY_OSES, runner.os) &&
          contains(env.DEPLOY_PYTHONS, matrix.python-version)
        run: |
          echo "PYB_EXTRA_ARGS=+upload" >> $GITHUB_ENV
      - shell: bash
        if: |
          matrix.with-venv == 'false'
        run: |
          echo "PYB_EXTRA_ARGS=$PYB_EXTRA_ARGS --no-venvs" >> $GITHUB_ENV
      - uses: pybuilder/build@master
        with:
          python-version: ${{ matrix.python-version }}
          pyb-extra-args: ${{ env.PYB_EXTRA_ARGS }}
          with-venv: ${{ matrix.with-venv }}
  build-summary:
    if: success() || failure()
    runs-on: ubuntu-latest
    name: Build Summary
    needs: build
    steps:
      - name: Check build matrix status
        if: needs.build.result != 'success'
        run: exit 1
